repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
        exclude: ^test/expected
    -   id: end-of-file-fixer
        exclude: ^test/expected
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: check-added-large-files
        args: ['--maxkb=500']
    -   id: mixed-line-ending
        args: ['--fix=lf']

-   repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
    -   id: black
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
        language_version: python3.12
