x-project-variables: &project-variables
  - ./project.env

services:
  db:
    container_name: pg_db
    build:
        context: .
        dockerfile: ./dockerfiles/db/Dockerfile
    volumes:
        - ./mike/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - 5406:${POSTGRES_PORT}
    command:
      - postgres
      - -c
      - wal_level=logical
      - -c
      - shared_preload_libraries=pg_stat_statements
    healthcheck:
      test: ["CMD-SHELL", "PGUSER=postgres", "pg_isready"]
      interval: 1s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  service:
    container_name: pg_service
    env_file: *project-variables
    build:
        context: .
        dockerfile: ./dockerfiles/python/Dockerfile
    volumes:
      - ./service:/app/service
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    depends_on:
      - db
